---
- name: mesos-agent
  hosts: '{{ target }}'
  gather_facts: yes
  vars:
    mesos_master: '{{ mesos_master }}'
  become: true
  become_user: root
  tasks:
    - name: package updates
      yum:
        name: '*'
        state: latest

    - name: mesos package
      package:
        name: https://dl.bintray.com/apache/mesos/el7/x86_64/mesos-1.8.1-1.el7.x86_64.rpm
        state: present
